Repository dev-AshishRanjan/Hacktoberfest-frontend, pull requests merged in 2023-10, with the labels that each got.

#1 ADD : Analog Clock Project
  contribution/ProjectList.json
  projects/Analog Clock/README.md
  projects/Analog Clock/alarm.js
  projects/Analog Clock/clock.html
  projects/Analog Clock/stylea.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#3 Clock_Ui Project added
  contribution/ProjectList.json
  projects/Clock_Ui/_config.yml
  projects/Clock_Ui/assets/css/styles.css
  projects/Clock_Ui/assets/js/main.js
  projects/Clock_Ui/assets/scss/styles.scss
  projects/Clock_Ui/index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XL

#4 Added web based Ping Pong game.
  contribution/ProjectList.json
  projects/Ping Pong/README.md
  projects/Ping Pong/index.html
  projects/Ping Pong/script.js
  projects/Ping Pong/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#5 Added GPACalculator Project
  projects/GPA Calculator/README.md
  projects/GPA Calculator/app.js
  projects/GPA Calculator/css/style.css
  projects/GPA Calculator/imgs/GPA-calc.png
  projects/GPA Calculator/imgs/early-birds.png
  projects/GPA Calculator/index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XL

#6 Dice game
  contribution/ProjectList.json
  projects/Dice-Game/README.md
  projects/Dice-Game/images/background.jpg
  projects/Dice-Game/images/dice1.png
  projects/Dice-Game/images/dice2.png
  projects/Dice-Game/images/dice3.png
  projects/Dice-Game/images/dice4.png
  projects/Dice-Game/images/dice5.png
  projects/Dice-Game/images/dice6.png
  projects/Dice-Game/images/favicon.ico
  projects/Dice-Game/index.html
  projects/Dice-Game/index.js
  projects/Dice-Game/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#8 Added GPA calculator project details in ./contribution/ProjectList.json
  contribution/ProjectList.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/S

#9 Memory card game
  contribution/ProjectList.json
  projects/Memory-Card-Game/images/img-1.png
  projects/Memory-Card-Game/images/img-2.png
  projects/Memory-Card-Game/images/img-3.png
  projects/Memory-Card-Game/images/img-4.png
  projects/Memory-Card-Game/images/img-5.png
  projects/Memory-Card-Game/images/img-6.png
  projects/Memory-Card-Game/images/img-7.png
  projects/Memory-Card-Game/images/img-8.png
  projects/Memory-Card-Game/images/que_icon.svg
  projects/Memory-Card-Game/index.html
  projects/Memory-Card-Game/script.js
  projects/Memory-Card-Game/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#10 Quiz app
  contribution/ProjectList.json
  projects/Quiz-App/README.md
  projects/Quiz-App/index.html
  projects/Quiz-App/js/questions.js
  projects/Quiz-App/js/script.js
  projects/Quiz-App/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XL

#11 Hangman game
  contribution/ProjectList.json
  projects/Hangman-Game/images/hangman-0.svg
  projects/Hangman-Game/images/hangman-1.svg
  projects/Hangman-Game/images/hangman-2.svg
  projects/Hangman-Game/images/hangman-3.svg
  projects/Hangman-Game/images/hangman-4.svg
  projects/Hangman-Game/images/hangman-5.svg
  projects/Hangman-Game/images/hangman-6.svg
  projects/Hangman-Game/images/lost.gif
  projects/Hangman-Game/images/victory.gif
  projects/Hangman-Game/index.html
  projects/Hangman-Game/scripts/script.js
  projects/Hangman-Game/scripts/word-list.js
  projects/Hangman-Game/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XL

#15 Added a project Stock-purchase
  projects/Stock-purchase/app.js
  projects/Stock-purchase/index.html
  projects/Stock-purchase/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#17 Updated: ProjectList.json
  contribution/ProjectList.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XS

#21 Avinash
  projects/Musically/PrioriSansOT-Regular.otf
  projects/Musically/Priori_Sans_Regular.ttf
  projects/Musically/css/style.css
  projects/Musically/img/AlanWalker.jpg
  projects/Musically/img/Drake.jpg
  projects/Musically/img/EdSheeran.jpg
  projects/Musically/img/EllieGoulding.jpg
  projects/Musically/img/Feel_Good.webp
  projects/Musically/img/Maroon5.jpg
  projects/Musically/img/Mood_Boosters.webp
  projects/Musically/img/Pop_Rocks.webp
  projects/Musically/img/SelenaGomez.jpg
  projects/Musically/img/TaylorSwift.jpg
  projects/Musically/img/adele.jpg
  projects/Musically/img/baby.jpg
  projects/Musically/img/blinding-ligghts.webp
  projects/Musically/img/charliePuth.jpg
  projects/Musically/img/chill.jpg
  projects/Musically/img/dusk-till-down.jpeg
  projects/Musically/img/electronic.jpeg
  projects/Musically/img/false-alarm.webp
  projects/Musically/img/first-kiss.jpg
  projects/Musically/img/heartless.webp
  projects/Musically/img/i-dont-care.jpg
  projects/Musically/img/i-feel-it-coming.webp
  projects/Musically/img/in-your-eyes.jpeg
  projects/Musically/img/kale-je.jpg
  projects/Musically/img/last-hurrah.jpeg
  projects/Musically/img/logo.png
  projects/Musically/img/logo1.svg
  projects/Musically/img/love-me.jpg
  projects/Musically/img/love-story.jpg
  projects/Musically/img/love.jpg
  projects/Musically/img/mia.jpg
  projects/Musically/img/mood.webp
  projects/Musically/img/nach.jpg
  projects/Musically/img/party.jpg
  projects/Musically/img/pop.jpg
  projects/Musically/img/profile.jpeg
  projects/Musically/img/retro.jpeg
  projects/Musically/img/roadtrip.jpg
  projects/Musically/img/rock.jpeg
  projects/Musically/img/secrets.webp
  projects/Musically/img/senorita.webp
  projects/Musically/img/set-fire.jpg
  projects/Musically/img/shawnmendes.jpg
  projects/Musically/img/shayad.jpeg
  projects/Musically/img/sorry-justin.png
  projects/Musically/img/sorry.webp
  projects/Musically/img/starboy.webp
  projects/Musically/img/tare-gin.jpeg
  projects/Musically/img/the-hills.webp
  projects/Musically/img/vaatthi.jpg
  projects/Musically/img/weeknd.jpg
  projects/Musically/img/weeknd1.jpg
  projects/Musically/img/workout.jpg
  projects/Musically/img/yummy.webp
  projects/Musically/index.html
  projects/Musically/playlist.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XXL

#18 Added a Navigation Menu which is responsive.
  contribution/ProjectList.json
  projects/Navigation Menu Responsive/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#22 Added my project Whos that Pokemon
  contribution/ProjectList.json
  projects/Who's that Pokemon/index.html
  projects/Who's that Pokemon/pokeball.png
  projects/Who's that Pokemon/script.js
  projects/Who's that Pokemon/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#23 Add Web Audio Drum Machine
  contribution/ProjectList.json
  projects/Web-Audio-Drum-Machine/generator.js
  projects/Web-Audio-Drum-Machine/index.html
  projects/Web-Audio-Drum-Machine/sequencer.js
  projects/Web-Audio-Drum-Machine/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, size/XL

#24 Create AnimatedSpinner.html
  projects/Animated Spinner/AnimatedSpinner.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#27 QR Code Generator
  contribution/ProjectList.json
  projects/QR Code Generator/QrCode.png
  projects/QR Code Generator/README.md
  projects/QR Code Generator/index.html
  projects/QR Code Generator/index.js
  projects/QR Code Generator/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#28 A Portfolio Website
  contribution/ProjectList.json
  projects/My-Portfolio/images/profile-pic.jpeg
  projects/My-Portfolio/index.html
  projects/My-Portfolio/style.css
Labels: good first issue, hacktoberfest, size/L

#29 Gym landing page
  contribution/ProjectList.json
  projects/Gym-Website/images/photo-1526506118085-60ce8714f8c5.jpg
  projects/Gym-Website/index.html
  projects/Gym-Website/style.css
  projects/My-Portfolio/images/profile-pic.jpeg
  projects/My-Portfolio/index.html
  projects/My-Portfolio/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#31 Added New project
  contribution/ProjectList.json
  projects/Simon_Game/game.js
  projects/Simon_Game/index.html
  projects/Simon_Game/introd.css
  projects/Simon_Game/introm.html
  projects/Simon_Game/sounds/blue.mp3
  projects/Simon_Game/sounds/green.mp3
  projects/Simon_Game/sounds/red.mp3
  projects/Simon_Game/sounds/wrong.mp3
  projects/Simon_Game/sounds/yellow.mp3
  projects/Simon_Game/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#32 added movie-sample-card
  contribution/ProjectList.json
  projects/Movie-Card-Sample/index.html
  projects/Movie-Card-Sample/movie-card.gif
  projects/Movie-Card-Sample/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#36 Added the Piano Project under Hacktoberfest 2023
  projects/Piano/index.html
  projects/Piano/index.js
  projects/Piano/notes/A.mp3
  projects/Piano/notes/Ab.mp3
  projects/Piano/notes/B.mp3
  projects/Piano/notes/Bb.mp3
  projects/Piano/notes/C.mp3
  projects/Piano/notes/D.mp3
  projects/Piano/notes/Db.mp3
  projects/Piano/notes/E.mp3
  projects/Piano/notes/Eb.mp3
  projects/Piano/notes/F.mp3
  projects/Piano/notes/G.mp3
  projects/Piano/notes/Gb.mp3
  projects/Piano/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#39 Added a Project- Calculator
  contribution/ProjectList.json
  projects/Calculator/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#40 Added Weather Application Project
  contribution/ProjectList.json
  projects/Weather-Application/images/L1.jpg
  projects/Weather-Application/index.js
  projects/Weather-Application/style2.css
  projects/Weather-Application/weather.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#41 fun maze game added
  contribution/ProjectList.json
  projects/Maze-Game/index.html
  projects/Maze-Game/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#42 mini project of login_form added
  contribution/ProjectList.json
  projects/login form/index.html
  projects/login form/main.js
  projects/login form/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/XL

#47 updated the responsiveness; issue: #46
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/M

#48 Added Temperature Converter
  contribution/ProjectList.json
  projects/TemperatureConverter/index.html
  projects/TemperatureConverter/script.js
  projects/TemperatureConverter/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#51 Add my project about the drawing website!
  contribution/ProjectList.json
  projects/Drawing-website/drawing.html
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#53 Added a simple chat bot with the interactive ui
  contribution/ProjectList.json
  projects/chat-bot/index,html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#54 Added folder from my project Hello from Brazil and contributor information.
  contribution/ProjectList.json
  projects/Hello from Brazil/brazil-flag.jpg
  projects/Hello from Brazil/index.html
  projects/Hello from Brazil/script.js
  projects/Hello from Brazil/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/M

#55 Updated ProjectList.json
  contribution/ProjectList.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/XS

#57 updated my-portfolio card
  projects/My-Portfolio/index.html
  projects/My-Portfolio/profile-pic.jpeg
  projects/My-Portfolio/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#58 Pull Request Management Project
  contribution/ProjectList.json
  projects/Pull Request Managment/index.html
  projects/Pull Request Managment/script.js
  projects/Pull Request Managment/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#59 Added Digital clock Frontend Project
  contribution/ProjectList.json
  projects/Digital_Clock/Readme.md
  projects/Digital_Clock/index.html
  projects/Digital_Clock/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#63 PDF viewer - nikhill56
  contribution/ProjectList.json
  projects/PDF Viewer/index.html
  projects/PDF Viewer/script.js
  projects/PDF Viewer/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/L

#64 fixed typo error
  contribution/ProjectList.json
  projects/Pull-Request-Management/index.html
  projects/Pull-Request-Management/script.js
  projects/Pull-Request-Management/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/M

#67 Added Music Player Application
  contribution/ProjectList.json
  projects/MusicPlayerApp/index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, size/M

#66 City Finder using Leaflet API
  contribution/ProjectList.json
  projects/City Finder/index.html
  projects/City Finder/script.js
  projects/City Finder/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L
