Repository dev-AshishRanjan/Hacktoberfest-Frontend, pull requests merged in 2023-10, with the labels that each got.

#1 added scroll bar code for js
  projects/ScrollBar/index.html
  projects/ScrollBar/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/L

#2 Fix Repo Typo
  app.js
  package.json
Labels: hacktoberfest, hacktoberfest-accepted, size/XS

#4 The Snake Game
  contribution/ProjectList.json
  projects/Snake_Game/index.html
Labels: hacktoberfest, hacktoberfest-accepted, size/S

#5 Animated count down eniola ademola
  contribution/ProjectList.json
  projects/Animated-Countdown/index.html
  projects/Animated-Countdown/script.js
  projects/Animated-Countdown/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#7 My data added
  contribution/ProjectList.json
Labels: size/XS

#8 Animated nav eniola ademola
  contribution/ProjectList.json
  projects/Animated-Navigation/index.html
  projects/Animated-Navigation/script.js
  projects/Animated-Navigation/style.css
Labels: hacktoberfest, hacktoberfest-accepted, size/L

#9 Create AnimatedSpinner.html
  projects/Spinner/AnimatedSpinner.html
Labels: hacktoberfest, size/L

#10 Background slider eniola ademola
  contribution/ProjectList.json
  projects/Background-Slider/index.html
  projects/Background-Slider/script.js
  projects/Background-Slider/style.css
Labels: hacktoberfest-accepted, size/L

#12 My project added
  contribution/ProjectList.json
  projects/Calculator-master/_config.yml
  projects/Calculator-master/index.html
  projects/Calculator-master/script.js
  projects/Calculator-master/style.css
  projects/Neuromorphism_Caculator/_config.yml
  projects/Neuromorphism_Caculator/index.html
  projects/Neuromorphism_Caculator/script.js
  projects/Neuromorphism_Caculator/style.css
Labels: hacktoberfest-accepted, size/XL

#14 Created QuizApp
  projects/QuizApp/index.html
  projects/QuizApp/script.js
  projects/QuizApp/style.css
Labels: hacktoberfest-accepted, size/L

#15 Blurry loader eniola ademola
  contribution/ProjectList.json
  projects/Blurry-Loading/index.html
  projects/Blurry-Loading/script.js
  projects/Blurry-Loading/style.css
Labels: hacktoberfest-accepted, size/M

#17 Faq eniola ademola
  contribution/ProjectList.json
  projects/FAQ-Collapse/index.html
  projects/FAQ-Collapse/script.js
  projects/FAQ-Collapse/style.css
Labels: hacktoberfest-accepted, size/L

#18 Create PencilTypeLoadingSpinner.html
  projects/Spinner/PencilTypeLoadingSpinner.html
Labels: hacktoberfest-accepted, size/L

#22 Create bio.html
  projects/bio/bio.html
Labels: size/L

#20 Details of QuizApp
  contribution/ProjectList.json
Labels: hacktoberfest-accepted, size/S

#23 Create Blog Post Webpage
  contribution/ProjectList.json
  projects/Blog Post/index.html
  projects/Blog Post/script.js
  projects/Blog Post/styles.css
Labels: hacktoberfest-accepted, size/L

#25 Simon game added
  contribution/ProjectList.json
  projects/Color_simon_game/game.js
  projects/Color_simon_game/index.html
  projects/Color_simon_game/sounds/blue.mp3
  projects/Color_simon_game/sounds/green.mp3
  projects/Color_simon_game/sounds/red.mp3
  projects/Color_simon_game/sounds/wrong.mp3
  projects/Color_simon_game/sounds/yellow.mp3
  projects/Color_simon_game/styles.css
Labels: enhancement, hacktoberfest-accepted, size/L

#24 Typing Progress Bar
  contribution/ProjectList.json
  projects/Typing Progress Bar/index.html
  projects/Typing Progress Bar/script.js
  projects/Typing Progress Bar/styles.css
Labels: hacktoberfest-accepted, size/M

#26 calculator type2 added
  contribution/ProjectList.json
  projects/calculator2/index.html
  projects/calculator2/script.js
  projects/calculator2/style.css
Labels: hacktoberfest-accepted, size/L

#27 Shopping cart
  contribution/ProjectList.json
  projects/ShoppingCart/images/apple.jpeg
  projects/ShoppingCart/images/basket.jpeg
  projects/ShoppingCart/images/fruit-plate.jpeg
  projects/ShoppingCart/images/glocery3.jpeg
  projects/ShoppingCart/images/glocery4.jpeg
  projects/ShoppingCart/images/glocery5.jpeg
  projects/ShoppingCart/images/vegetable-logo.jpeg
  projects/ShoppingCart/images/vegetable2.png
  projects/ShoppingCart/images/vegetable3.png
  projects/ShoppingCart/images/vegetables1.jpeg
  projects/ShoppingCart/index.css
  projects/ShoppingCart/index.html
Labels: size/L

#28 Car Price Filter
  contribution/ProjectList.json
  projects/Car Price Filter/index.html
  projects/Car Price Filter/script.js
  projects/Car Price Filter/styles.css
Labels: hacktoberfest-accepted, size/L

#29 Resolve the issue-(#16) of Contact Page.
  contact.html
Labels: enhancement, hacktoberfest-accepted, size/S

#30 Added to-do list project
  contribution/ProjectList.json
  projects/ToDoList/index.html
  projects/ToDoList/script.js
  projects/ToDoList/styles.css
Labels: hacktoberfest-accepted, size/L

#31 added lazy loader
  contribution/ProjectList.json
  projects/Lazy-loader/app.js
  projects/Lazy-loader/index.html
  projects/Lazy-loader/style.css
Labels: enhancement, hacktoberfest-accepted, size/M

#34 improvements: updated the UI to clear after 1m, added download QR option
  projects/QR Code Generator/README.md
  projects/QR Code Generator/index.html
  projects/QR Code Generator/index.js
  projects/QR Code Generator/style.css
Labels: enhancement, hacktoberfest-accepted, size/M

#35 Add: youtube video id finder
  contribution/ProjectList.json
  projects/Youtube video Id Finder/index.html
Labels: hacktoberfest-accepted, size/M

#37 Light/Dark Mode Toggle added
  contribution/ProjectList.json
  projects/Light-Dark-Mode-Toggle/README.md
  projects/Light-Dark-Mode-Toggle/dark.png
  projects/Light-Dark-Mode-Toggle/index.html
  projects/Light-Dark-Mode-Toggle/light.png
  projects/Light-Dark-Mode-Toggle/style.css
Labels: enhancement, hacktoberfest-accepted, size/L

#39 Added random meme generator
  contribution/ProjectList.json
  projects/RandomMemeGenerator/index.html
  projects/RandomMemeGenerator/script.js
  projects/RandomMemeGenerator/styles.css
Labels: hacktoberfest-accepted, size/L

#40 added emoji catcher game for website
  contribution/ProjectList.json
  projects/Emoji_Catcher_Game/app.js
  projects/Emoji_Catcher_Game/index.html
  projects/Emoji_Catcher_Game/style.css
Labels: size/L

#41 add project login page
  contribution/ProjectList.json
  projects/Login-Page/assets/images/background.jpg
  projects/Login-Page/assets/images/logo.png
  projects/Login-Page/assets/styles/index.css
  projects/Login-Page/index.html
Labels: hacktoberfest-accepted, size/L

#44 Add: New project Stopwatch
  contribution/ProjectList.json
  projects/Stopwatch/index.html
  projects/Stopwatch/script.js
  projects/Stopwatch/style.css
Labels: hacktoberfest-accepted, size/L

#46 add: New Project - Notes App
  contribution/ProjectList.json
  projects/Notes-App/index.html
  projects/Notes-App/script.js
  projects/Notes-App/style.css
Labels: hacktoberfest-accepted, size/XL

#48 made relevant edits in Readme
  README.md
Labels: size/XS

#49 Random quote app
  projects/Random_Quote_App/index.html
  projects/Random_Quote_App/script.js
  projects/Random_Quote_App/styles.css
Labels: hacktoberfest-accepted, size/L

#50 Finance app added
  CONTRIBUTING.md
  projects/finance-app/Procfile
  projects/finance-app/__MACOSX/._Procfile
  projects/finance-app/__MACOSX/._requirements.txt
  projects/finance-app/__MACOSX/._runtime.txt
  projects/finance-app/__MACOSX/._script1.py
  projects/finance-app/__MACOSX/._static
  projects/finance-app/__MACOSX/._templates
  projects/finance-app/__MACOSX/static/._css
  projects/finance-app/__MACOSX/static/css/._main.css
  projects/finance-app/__MACOSX/templates/._about.html
  projects/finance-app/__MACOSX/templates/._home.html
  projects/finance-app/__MACOSX/templates/._layout.html
  projects/finance-app/__MACOSX/templates/._plot.html
  projects/finance-app/requirements.txt
  projects/finance-app/runtime.txt
  projects/finance-app/script1.py
  projects/finance-app/static/css/main.css
  projects/finance-app/templates/about.html
  projects/finance-app/templates/home.html
  projects/finance-app/templates/layout.html
  projects/finance-app/templates/plot.html
Labels: hacktoberfest-accepted, size/L

#51 Rick and Morty | A simple web application that uses Rick Morty API
  contribution/ProjectList.json
  projects/Rick_Morty_Encyclopedia/public/index.html
  projects/Rick_Morty_Encyclopedia/public/src/assets/Rick-morty-favicon.ico
  projects/Rick_Morty_Encyclopedia/public/src/css/index.css
  projects/Rick_Morty_Encyclopedia/public/src/js/app.js
  projects/Rick_Morty_Encyclopedia/readMe.md
Labels: hacktoberfest-accepted, size/L

#52 i Added Javascript game which was created using html css js
  contribution/ProjectList.json
  projects/shooting game/Images/angler1.png
  projects/shooting game/Images/angler2.png
  projects/shooting game/Images/drone.png
  projects/shooting game/Images/fireExplosion.png
  projects/shooting game/Images/gears.png
  projects/shooting game/Images/hivewhale.png
  projects/shooting game/Images/layer1.png
  projects/shooting game/Images/layer2.png
  projects/shooting game/Images/layer3.png
  projects/shooting game/Images/layer4.png
  projects/shooting game/Images/lucky.png
  projects/shooting game/Images/player.png
  projects/shooting game/Images/projectile.png
  projects/shooting game/Images/smokeExplosion.png
  projects/shooting game/README.md
  projects/shooting game/game.html
  projects/shooting game/game.js
  projects/shooting game/hit.mp3
  projects/shooting game/style.css
Labels: hacktoberfest-accepted, size/XL

#53 add color selector
  contribution/ProjectList.json
  projects/Color_Selector/index.html
  projects/Color_Selector/index.js
  projects/Color_Selector/styles.css
Labels: hacktoberfest-accepted, size/M

#55 Fix: Added redirect link to navbar logo and cursor pointer on theme logo
  contact.html
  contributors.html
  index.html
  style.css
Labels: hacktoberfest-accepted, size/XS

#56 Added a BMI Calculator
  contribution/ProjectList.json
  projects/BMI Calculator/IMG01.jpg
  projects/BMI Calculator/IMG02.png
  projects/BMI Calculator/index.html
  projects/BMI Calculator/index2.html
Labels: hacktoberfest-accepted, size/L

#57 Updated my own project
  projects/coffeeshop/cart.js
  projects/coffeeshop/css/styles.css
  projects/coffeeshop/img/icon.ico
  projects/coffeeshop/img/press/ccd.png
  projects/coffeeshop/img/press/costa-coffee.jpg
  projects/coffeeshop/img/press/illy.png
  projects/coffeeshop/img/press/starbucks.png
  projects/coffeeshop/index.html
  projects/coffeeshop/netbank.js
  projects/coffeeshop/payment.html
  projects/coffeeshop/top.js
Labels: hacktoberfest-accepted, size/XXL

#59 Portfolio website and update ProjectList Fixes #58
  contribution/ProjectList.json
  projects/Portfolio/img/background.png
  projects/Portfolio/img/favicon.png
  projects/Portfolio/img/main.jpg
  projects/Portfolio/index.html
  projects/Portfolio/style.css
Labels: hacktoberfest-accepted, size/XL

#60 added password generator
  contribution/ProjectList.json
  projects/Password Generator/password.html
  projects/Password Generator/password.js
Labels: hacktoberfest-accepted, size/XL

#64 Updates repo
  contribution/ProjectList.json
  projects/resume project/resume.html
Labels: hacktoberfest-accepted, size/L

#65 fitness-tracker-added
  contribution/ProjectList.json
  projects/fitness-tracker/index.html
  projects/fitness-tracker/script.js
  projects/fitness-tracker/styles.css
Labels: hacktoberfest-accepted, size/L

#66 Food Market System
  contribution/ProjectList.json
  projects/Food Market/apple.jpg
  projects/Food Market/apple.webp
  projects/Food Market/banana.png
  projects/Food Market/carrot.jpg
  projects/Food Market/chicken.jpg
  projects/Food Market/index.html
Labels: hacktoberfest-accepted, size/L

#70 Added Expense Tracker
  contribution/ProjectList.json
  projects/ExpenseTracker/index.html
  projects/ExpenseTracker/script.js
  projects/ExpenseTracker/style.css
Labels: hacktoberfest-accepted, size/L

#72 Color Pointer & Picker
  contribution/ProjectList.json
  projects/Color-Picker/index.html
  projects/Color-Picker/script.js
  projects/Color-Picker/styles.css
Labels: hacktoberfest-accepted, size/L
